### ISSUE TITLE
explore the usage of extensions

### ISSUE THREAD

**Issue by oodrand** [KaityXD/Mayumi#1]
whaddya think?

**Comment by KaityXD** [comment]
interesting

**Comment by oodrand** [comment]
yes, very interesting

**Comment by oodrand** [comment]
anyway, it looks like a simpler alternative to the modular cog system we have right now

**Comment by KaityXD** [comment]
there is nothing here

**Comment by oodrand** [comment]
there is something here, actually.

**Comment by KaityXD** [comment]
oh yeah

**Comment by oodrand** [comment]
closed
